# Generated by Django 3.1 on 2020-08-11 23:02

import catalog.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_blanks', models.PositiveSmallIntegerField(default=1, validators=[catalog.models.v_FB], verbose_name='Number of blanks')),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('FB', 'Fill in the Blank'), ('MA', 'Multiple Answer'), ('MC', 'Multiple Choice'), ('SA', 'Short Answer'), ('TF', 'True/False')], default='MC', help_text='question format', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.CharField(choices=[('T', 'True'), ('F', 'False')], default='T', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique ID for this question', primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.format')),
            ],
        ),
    ]
