# Generated by Django 3.1 on 2020-08-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200811_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='format',
            field=models.CharField(choices=[('FB', 'Fill in the Blank'), ('MA', 'Multiple Answer'), ('MC', 'Multiple Choice'), ('SA', 'Short Answer'), ('TF', 'True/False')], default='MC', help_text='question format', max_length=2),
        ),
        migrations.DeleteModel(
            name='Format',
        ),
    ]
