# Generated by Django 3.1 on 2020-08-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200811_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_responses',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
